apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: unleash-dev-claim
    namespace: unleash-dev
  persistentVolumeReclaimPolicy: Delete
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
